# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

python:
  install:
    # 安装你的项目（可选，如果文档里需要 import droso 之类的包）
    - method: pip
      path: .

    # 安装构建文档所需的依赖（Sphinx、主题等）
    - requirements: docs/requirements.txt
